### ISSUE TITLE
Help needed with running development environment

### ISSUE THREAD

**Issue by dimagimburg** [petecorreia/react-circular-input#14]
Hey, I want to add a feature to react circular input. 

Can you please guide me how do I run the local development environment easily so I can reflect the changes I do in the code some rendered example? thanks. 

(this is the first time I contribute to a project with such structure)

**Comment by dimagimburg** [comment]
Nevermind, figured it out :) used npm link

**Comment by petecorreia** [comment]
Ah great that you cracked it. I didn't get to this fast enough :)

If you're wanting to enrich the library, you can clone it locally and use the various npm scripts like 
`npm run start`.

I usually go for `npm run docs:dev` as it lets you develop features and document at the same time via having examples of what you want to improve upon.

Hope this helps even if you're already sorted

**Comment by dimagimburg** [comment]
@petecorreia thank you very much, hope I can contribute.
