### ISSUE TITLE
Custom Progess Component

### ISSUE THREAD

**Issue by wtLau** [petecorreia/react-circular-input#23]
Hi,

Thanks for this awesome library!

Problem: I want to have an initial progress component that is read-only and styled with a lighter color. It is used as a reference to the previous value submitted.

Is it possible to have an additional `<CircularProgress />` within `CircularInput` that takes a different `value`?

**Comment by petecorreia** [comment]
> Thanks for this awesome library!

Happy to help!

> Problem: I want to have an initial progress component that is read-only and styled with a lighter color. It is used as a reference to the previous value submitted.
>
> Is it possible to have an additional <CircularProgress /> within CircularInput that takes a different value?

Let me see if I get the problem: you want 2 progress circles where one of them has a derived value from the first one?

Would something like this work:

```typescript
import {
	CircularInput,
	CircularTrack,
	CircularProgress,
	CircularThumb,
} from 'react-circular-input'

export default () => {
	const [value, setValue] = useState(0.25)

    const derivedValue = value * 2

	return (
		<>
            <CircularInput value={value} onChange={setValue}>
                <CircularTrack />
                <CircularProgress />
                <CircularThumb />
            </CircularInput>

            <CircularInput value={derivedValue}>
                <CircularProgress />
            </CircularInput>
        </>
	)
}
```

Let me know if I understood it wrong!

**Comment by wtLau** [comment]
Thank you for replying!

The example would be very close to what I am looking for, but I would like to have two progress circles in under CicularInput. One is using `derived values` and the other one is using `value`

**Comment by petecorreia** [comment]
Sorry for delay in replying!

I would suggest an actual custom progress component that you can off of the implementation of CircularProgress and that receives the value rather than reading it from context.

It's a very trivial component, only a few lines of code! https://github.com/petecorreia/react-circular-input/blob/master/src/CircularProgress.tsx

**Comment by wtLau** [comment]
Thanks for the reply!

Understood! I will give it a try. Thanks for the pointer
